### ISSUE TITLE
Version Control and Workflow

### ISSUE THREAD

**Issue by bjfultn** [Keck-DataReductionPipelines/KeckDRPFramework#10]
It's time to establish a version control system since we have multiple pipelines depending on this Framework. I need to be able to add a specific version/tag of this framework into my `requirements.txt` file(s) so that API updated to the framework don't break our KPF code. It looks like you have the infrastructure set up for this already so we just need to start using it and incrementing the version.

In addition, I recommend establishing a more rigid procedure for code development/contributions/releases at this point. I suggest following the GitFlow workflow (https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), but I'm open to others if preferred.

**Comment by shkw0k** [comment]
We are not quite stable yet, but getting close.

**Comment by shkw0k** [comment]
We have now a develop branch. 
We need to agree to went to make a release branch.
This develop branch has the PEP8 changes. So filenames and class names have changed.
We need a more or less functioning pipeline before we can call the framework stable.

**Comment by lucarizzi** [comment]
We discussed the git workflow at a meeting today. We all agree on the described workflow.

In summary, for now we have decided:

1- Development will continue on the development branch
2- We are working towards a version 1 stable release
3- As soon as the development branch is close enough, we will branch off into a version 1 release branch
4- The version 1 release branch will become master once it is released
