### ISSUE TITLE
Default configurations

### ISSUE THREAD

**Issue by qwang3** [Keck-DataReductionPipelines/KeckDRPFramework#27]
It would be nice if there is some sort of validation process that checks the framework configuration file, and make sure that all the mandatory configs are present before initializing the framework. In the case that a configuration is missing, the framework may fail to initialize, or resort to a default value and log a warning. 

The framework technically is only concerned with configurations relevant to the framework. I think it is a good idea if the framework assumes that the pipeline can handle any of the pipeline's own missing configurations.

**Comment by shkw0k** [comment]
Updated framework_config.py with default config values.
