### ISSUE TITLE
Trouble Getting Started

### ISSUE THREAD

**Issue by bjfultn** [Keck-DataReductionPipelines/KeckDRPFramework#3]
I'm trying to set up a very simple script to set up a Framework based on the KCWI examples. 

```
class KPF0to1(Base_pipeline):
    """
    Convenience Pipeline to Process KPF data from 0 to 1
    """

    event_table = {"subtract_bias": ("level0_subtract_bias", ),
                   "divide_flat": ("level0_divide_flat", ),
                   }

    def __init__(self, data=None):
        """
        Constructor
        """
        Base_pipeline.__init__(self)

        self.data = data

        self.args = Arguments(name="kpf0", data=data)

    def action_planner(self, action, context):
        context.append_event("subtract_bias", self.args)


pipeline = KPF0to1()

default_framework_config = 'configs/framework.cfg'

framework = Framework(KPF0to1, default_framework_config)
framework.config.instrument = ConfigClass("configs/default.cfg")
framework.logger.info("Framework initialized")

for i in range(10):
    args = Arguments(data=kpf0)
    framework.logger.info("Processing file {:d}".format(i))
    framework.append_event('subtract_bias', args)

framework.start()
framework.waitForEver()
```

First, I get the following error:
```
Traceback (most recent call last):
  File "/Users/bfulton/code/KeckDRPFramework/keckdrpframework/core/framework.py", line 364, in find_pipeline
    module = importlib.import_module(full_name)
  File "/Volumes/Mars/anaconda3/envs/kpf/lib/python3.7/importlib/__init__.py", line 118, in import_module
    if name.startswith('.'):
AttributeError: type object 'KPF0to1' has no attribute 'startswith'
```

It appears that the `Framework` object wants the first argument to be a string, but the KCWI example gives a `Pipeline` object. The `reduce.py` script in the KCWI_DRP repo fails in this way too.

If I try to catch this scenario and allow the `Pipeline` object to populate the `Framework.pipeline` attribute directly. I get further but eventually hit other weird errors that don't make sense to me.

```
2019-10-07 22:56:19:DRPF:INFO: Framework initialized
2019-10-07 22:56:19:DRPF:INFO: Processing file 0
2019-10-07 22:56:19:DRPF:INFO: Processing file 1
2019-10-07 22:56:19:DRPF:INFO: Processing file 2
2019-10-07 22:56:19:DRPF:INFO: Processing file 3
2019-10-07 22:56:19:DRPF:INFO: Processing file 4
2019-10-07 22:56:19:DRPF:INFO: Processing file 5
2019-10-07 22:56:19:DRPF:INFO: Processing file 6
2019-10-07 22:56:19:DRPF:INFO: Processing file 7
2019-10-07 22:56:19:DRPF:INFO: Processing file 8
2019-10-07 22:56:19:DRPF:INFO: Processing file 9
2019-10-07 22:56:19:DRPF:ERROR: Exception while processing action , event_to_action() missing 1 required positional argument: 'context'
2019-10-07 22:56:19:DRPF:INFO: Framework main loop started
Traceback (most recent call last):
  File "/Users/bfulton/code/KeckDRPFramework/keckdrpframework/core/framework.py", line 244, in main_loop
    action = self.event_to_action (event, self.context)
  File "/Users/bfulton/code/KeckDRPFramework/keckdrpframework/core/framework.py", line 174, in event_to_action
    event_info = self.pipeline.event_to_action (event, context)
TypeError: event_to_action() missing 1 required positional argument: 'context'
```

Any ideas?

**Comment by lucarizzi** [comment]
You catch me at a rather difficult time: I am at ADASS in the Netherlands so I don't have a lot of time but I need to warn you that the interface to the pipeline has changed a bit from the time we last talked and from the time I wrote the documentation. Specifically, Shui has added the feature that your team was looking for (parallelization) but I suspect that enough changes where introduced in the framework that my examples might not work anymore.

I might still be able to help you. 
Could you send me the entire list of files you are using? you provably have a fits file of some kind, a startup script,  and the pipeline definition file.

**Comment by bjfultn** [comment]
The `kpf0` object I'm sending as an argument is a KPF Level 0 data model. So I'm not passing any fits files or paths to fits files. I haven't got as far as setting up the `subtract_bias` method as a primitive because I think I'm hitting this `TypeError` before it gets a chance to try to call it (although I could be wrong about that). 

I think that maybe the first step to help would be just to see if you can get your KCWI example running again. At this point I don't know if we are seeing a bug in my code (likely) or the Framework itself. If you can get the KCWI script running again that would help to eliminate the latter scenario.

**Comment by shkw0k** [comment]
Indeed I made some changes that broke the KCWI example. 
However, in the directory examples, you can find a very simple working pipeline, that can do multi-processing.  I have not yet updated the documentation. 
You may need to change runTest_harness.sh for your environment.
And also review config.cfg for your needs.

**Comment by bjfultn** [comment]
I don't see an examples directory in the top-level. Is it in a sub-directory?

**Comment by shkw0k** [comment]
I'm sorry. My mistake, I didn't push.
They are there now. There is also a unit_test directory.

**Comment by bjfultn** [comment]
Thanks for uploading the new docs. I have a good start and a working KPF pipeline now using the KeckDRPF. I'm still a little unclear about how to use the multiprocessing abilities, but I don't need that yet and I don't plan on implementing that until I do.
