### ISSUE TITLE
Arguments class is overly limited

### ISSUE THREAD

**Issue by daverumph** [Keck-DataReductionPipelines/KeckDRPFramework#32]
The current models.arguments.Arguments class, used for both input parameters and return values of primitives, requires all parameters to be named (keyworded), since it uses the arguments object's dictionary internally. This means that primitive developers must be aware of the names used by developers of other primitives in the pipeline.  This couples the primitive development unnecessarily.

It would be better to support both positional and keyword arguments.  This is especially relevant for primitive module output.

I am a senior software engineer with Caltech's Schmidt Academy working Qifan Wang, and I have developed a small KpfArguments class that derives from Arguments in a backwards-compatible way and supports both positional and keyword arguments.  I'm recommending that it be used in place of Arguments for all primitives developed for the KPF pipeline.  I would be happy for the extended capabilities of KpfArguments to be added to Arguments, and would be glad to work with someone to make it happen.  Below is the code for KpfArguments.py

`# kpf_arguments.py

"""
KpfArguments is a class derived from Arguments.
The purpose is to extend the capabilities of an arguments class to support
both keyword and positional arguments in a clean and convenient way.
The current Arguments class only supports keyword arguments, which is
especially limiting for return values from functions.  It means that
developers of pipelines and other functions must know the keywords used by
the developer of other functions internal to those functions.
"""

from keckdrpframework.models.arguments import Arguments

class KpfArguments(Arguments):
    """
    KpfArguments class
    Extends Arguments to support positional arguments in addition
    to keywoard arguments.
    Positional arguments are stored on an internal args list.
    Support is included for indexing the KpfArguments class.  Doing
    so only gives or sets positional arguments.  keyword arguments
    are not accessible via the index.
    append and pop are also supported via passthru.
    """

    def __init__(self, *args, **kwargs):
        Arguments.__init__(self)
        self.name = "undef"
        self._kpfargs = []
        self._kpfargs.extend(args)
        self.__dict__.update(kwargs)

    def __str__(self):
        out = []
        [out.append(f"{arg}") for arg in self._kpfargs]
        [out.append(f"{k}: {v}") for k, v in self.__dict__.items() if k != '_kpfargs']
        return ", ".join(out)

    def __iter__(self):
        return iter(self._kpfargs)
    
    def __getitem__(self, ix):
        return self._kpfargs.__getitem__(ix)
    
    def __setitem__(self, ix, val):
        self._kpfargs.__setitem__(ix, val)

    def insert(self, ix, val):
        self._kpfargs.insert(ix, val)

    def append(self, val):
        self._kpfargs.append(val)
    
    def pop(self):
        return self._kpfargs.pop()

    def __len__(self):
        return len(self._kpfargs)

**Comment by shkw0k** [comment]
This is a good idea.
We can merge this feature into the Arguments class.
Note that this Argument class will need to be pickable when used in the multiprocessing mode.

**Comment by daverumph** [comment]
I assume you mean pickleable.  (Probably "fixed" for you by spellcheck.). Nothing I've done precludes that.

**Comment by shkw0k** [comment]
Thank you for the correction.

**Comment by daverumph** [comment]
How would you like to handle this?  Would you like me to do the development in another branch and submit a pull request?  Would you like to do the merge yourself based on the code I included in the original post?

**Comment by lucarizzi** [comment]
Dave,

I suggest you branch off the current development branch and then issue a pull request.

Thank you for your contributions: I agree with Shui that this is a great idea!

Luca

**Comment by daverumph** [comment]
I just tried to push my "arguments" branch, but permission is denied.  Maybe I need to be added to the "contributors"?

**Comment by lucarizzi** [comment]
Yes probably

I’ll do it right away

**Comment by daverumph** [comment]
Hmmm.  I accepted your invitation, but KeckDRPFramework repository still only lists 2 contributors, and when I try to push, it's still forbidden.  Is there something else that needs to be done?

**Comment by shkw0k** [comment]
I made the changes in Arguments and pushed them to master.
I also added one new test case in unit_tests/test_models.py

**Comment by daverumph** [comment]
I'm both glad and sorry to hear that.  I have an updated version that I have been trying to push.  Here is the source:

---------------

`# arguments.py
"""
Created on Jul 9, 2019
Significantly extended Mar 29, 2020

@author: skwok, daverumph

Arguments is a class to support both keyword and positional arguments
in a clean and convenient way.
Note that __len__ and __iter__ only allow access to the positional
arguments.  This is because dict and sequence iterators have different
behaviors, namely, dict iterators only return keys, while sequence
iterators return values.  Since it isn't possible in in some cases to
distinguish a value from a key, it doesn't make sense to provide
combined access to both positional and keyword arguments through the
same iterator.  Likewise, __len__ only counts positional arguments.
If you want to count or iterate through the keyword entries, use
len_kw or iter_kw, respectively.
Indexing, however, can be used with either numbers or strings.
Numerical indexes access positional arguments, while strings are
treated as keywords.
"""


class Arguments(object):
    """
    Arguments class
    Positional arguments are stored on an internal args list.
    Support is included for indexing the Arguments class.  Doing
    so only gives or sets positional arguments.  Keyword arguments
    are not accessible via the index.
    insert, append, pop and iter() of positional arguments are also
    supported via passthru
    keyword arguments can also be iterated
    """

    def __init__(self, *args, **kwargs):
        self.name = "undef"
        self._pos_args = []
        self._pos_args.extend(args)
        self.__dict__.update(kwargs)
    
    # access all items
    def __str__(self):
        out = []
        [out.append(f"{arg}") for arg in self._pos_args]
        [out.append(f"{k}: {v}") for k, v in self.__dict__.items() if k != '_pos_args']
        return ", ".join(out)

    def __getitem__(self, ix):
        if isinstance(ix, str):
            return self.__dict__.__getitem__(ix)
        return self._pos_args.__getitem__(ix)
    
    def __setitem__(self, ix, val):
        if isinstance(ix, str):
            self.__dict__.__setitem__(ix, val)
        else:
            self._pos_args.__setitem__(ix, val)

    # access positional arguments
    def __len__(self):
        """
        count of positional arguments stored
        """
        return len(self._pos_args)

    def __iter__(self):
        """
        iterator of positional arguments
        """
        return iter(self._pos_args)
    
    def insert(self, ix, val):
        """
        insert a positional argument before ix
        """
        self._pos_args.insert(ix, val)

    def append(self, val):
        """
        append a positional argument at the end
        """
        self._pos_args.append(val)
    
    def pop(self):
        """
        return and remove the last positional argument
        """
        return self._pos_args.pop()

    def extend(self, *args):
        """
        add the supplied values to the positional arguments at the end
        """
        self._pos_args.extend(args)

    # access keyword arguments
    def iter_kw(self):
        """
        iterator of the keyword arguments
        excludes the internally used '_pos_args'
        """
        for k in self.__dict__.keys():
            if k == '_pos_args':
                continue
            yield k

    def len_kw(self):
        """
        count of keyword arguments, including 'name'
        excludes the internally used '_pos_args'
        """
        # subtract one to account for _pos_args, which
        # is excluded from iteration and shouldn't be
        # directly accessed.  "name" is counted, however.
        return max(0, self.__dict__.__len__() - 1)

    def update(self, **kwargs):
        """
        add or replace supplied arguments to the keyword arguments dictionary.
        Shouldn't update '_pos_args' using this!
        """
        self.__dict__.update(kwargs)
`

**Comment by lucarizzi** [comment]
Dave
I tried to add you to the external collaborators.

Did you get the invite?

**Comment by daverumph** [comment]
Yes, and I responded and seemed to be added, but still had permission problems.  I'll try again with the link you just resent.

**Comment by daverumph** [comment]
The automatic response e-mail is below.  I don't know if this is significant, but it says it gives me "read" access to 1 repository.

Dave
------------
On Mar 30, 2020, at 1:38 PM, Keck DRPs <noreply@github.com> wrote:

You’ve been added to the DRP Framework team for the Keck DRPs organization.  DRP Framework has 7 members and gives *read* access to 1 Keck-DataReductionPipelines repository.

View DRP Framework: https://github.com/orgs/Keck-DataReductionPipelines/teams/drp-framework

Read more about team permissions here: https://help.github.com/articles/what-are-the-different-access-permissions

**Comment by daverumph** [comment]
Oh, I think I see what's wrong.  I have access to the archived "DRP Framework" repository, not the KeckDRPFramework one.

**Comment by daverumph** [comment]
The repository needs to be updated on the "DRP Framework" team settings.

**Comment by daverumph** [comment]
That worked.  I'll post a pull request shortly.

**Comment by shkw0k** [comment]
Merged to master.
