### ISSUE TITLE
Supported platforms

### ISSUE THREAD

**Issue by awhoward** [Keck-DataReductionPipelines/KeckDRPFramework#45]
For the KPF Pipeline, we are thinking about what platforms (Mac OS, Linux variants, possibly Windows) should be supported.  We are considering ways to set up automated procedures to test building the packages (minimum) and possibly additional tests.

Does the WMKO Framework have a requirement for supported platforms?   The KPF Pipeline's requirements should probably flow down from the Framework's.

Tagging interested folks: @bjfultn @qwang3

**Comment by GBruceB** [comment]
very few astronomers use Windows  - Mac OS, *nix should fit the bill

Bruce

On Jun 12, 2020, at 2:55 PM, Andrew Howard <notifications@github.com<mailto:notifications@github.com>> wrote:



For the KPF Pipeline, we are thinking about what platforms (Mac OS, Linux variants, possibly Windows) should be supported. We are considering ways to set up automated procedures to test building the packages (minimum) and possibly additional tests.

Does the WMKO Framework have a requirement for supported platforms? The KPF Pipeline's requirements should probably flow down from the Framework's.

Tagging interested folks: @bjfultn<https://github.com/bjfultn> @qwang3<https://github.com/qwang3>

**Comment by shkw0k** [comment]
We do not plan to support MS Windows.
Mac OS and Unix-like platforms are supported.

**Comment by awhoward** [comment]
Thanks.  We will plan to support Mac OS and Unix variants with the KPF Pipeline.
