### ISSUE TITLE
Pipeline Documentation

### ISSUE THREAD

**Issue by awhoward** [Keck-DataReductionPipelines/KeckDRPFramework#46]
We are working on documentation for the KPF pipeline.  Thus far we have used readthedocs (which requires a paid account while the repository is private for the next ~2 years as we develop the pipeline).  It appears that the WMKO Framework also uses readthedocs.  Please advise if we should use another documentation platform as this will be handed off to WMKO when we release the pipeline.

I'm posting this issue here (instead of sending an email) since it may affect other pipelines.

**Comment by lucarizzi** [comment]
Hi Andrew

Yes indeed we are standardizing documentation on read the docs 

I wasn’t aware that you needed a paid subscription for a private repository. If that becomes an issue, the workaround would be to keep the docs local and compile them with Sphinx and only release them when you are ready. 

If instead you are comfortable with the paid subscription to read the docs then you are already doing the right thing

**Comment by awhoward** [comment]
We prefer hosted documentation because it allows for separate docs for different git versions of the code (instead of just master).  It seems possible, but cumbersome and time-consuming to set this up on a local server.  Having easy-to-view docs for feature branches will encourage developers to write and refine the documentation as they go, rather than as a catchup exercise when features are pushed to master.

**Comment by lucarizzi** [comment]
Oh absolutely, I couldn’t agree more.

In fact, we are adding hosted documentation as a requirement on our DRP ICD.

I was a bit concerned about the fact that you need to use a paid version, but if that is not an issue, we support your choice.

**Comment by lucarizzi** [comment]
Answer is satisfactory
