### ISSUE TITLE
Automated testing of pipeline exceptions

### ISSUE THREAD

**Issue by daverumph** [Keck-DataReductionPipelines/KeckDRPFramework#47]
The KPF Pipeline needs to be able to test situations where its recipe processing can throw exceptions, such as "BadRecipe".  I have supported this in my local version of framework.py by enabling a new "testing" mode.  When the framework object's testing class member is True, caught exceptions in execute and main_loop are raised again, to be caught by the testing environment rather than by the framework.  With your approval, I intend to push the changes in a new branch, feature/exception_testing, and issue a pull request for you to merge it.

**Comment by daverumph** [comment]
Also, processing_context.py has the recently added append_new_event(), but I think the naming is consistent with the previous push_event().  They should both include "_new_" in the name, or neither should have it.  There is no difference in behavior regarding the newness of the Event between the two, so the difference in naming is misleading.

**Comment by shkw0k** [comment]
Added on_error callback method as a hook for the pipeline to handle the exception.
See unit_tests/test_run_example.py.
Note that there also on_state() to intercept the state and modify it if desired.

The PR with the testmode flag is also available.
