### ISSUE TITLE
Ingest data fails quietly

### ISSUE THREAD

**Issue by joshwalawender** [Keck-DataReductionPipelines/KeckDRPFramework#49]
When building a simple framework, I found that if I passed a single file to `framework.ingest_data`, for example:

```
framework.ingest_data(None, args.file, False)
```

it would fail to process the file.  If I pass the same file as a list:

```
framework.ingest_data(None, [args.file], False)
```

it works fine.  We should probably modify `ingest_data` so that it either processes a string argument or it spits out an informative message.

**Comment by shkw0k** [comment]
No ingest_data can take a name of a list of names.
Will give warning if files do not exist.
