### ISSUE TITLE
Full Module Paths To Primitives

### ISSUE THREAD

**Issue by bjfultn** [Keck-DataReductionPipelines/KeckDRPFramework#5]
I don't like having to do `from x import *` since it quickly becomes unclear where classes or functions are defined.

With the current action framework it doesn't seem to work with an action defined like `kpfpipe.primitives.level1.correct_telluric_lines`. Instead I must first do `from kpfpipe.primitives.level1 import *` then use only `correct_telluric_lines` as the action name.

**Comment by shkw0k** [comment]
You can also do from kpfpipe.primitives.level1 import correct_telluric_lines, other_names, more_names

**Comment by bjfultn** [comment]
True, but this still forces unique primitive names then. For example I can't have a `kpfpipe.primitives.level0.divide_flat` and also `kpfpipe.primitives.level1.divide_flat` (not sure I need that, but still). Is there a technical reason why we can't use the full module paths?

**Comment by shkw0k** [comment]
I think it should do full paths also. 
This may be a bug.

**Comment by shkw0k** [comment]
Full paths in action should work now.
The root of the path must be included in PYTHONPATH or in config.primitive_path.

**Comment by bjfultn** [comment]
I think this has been implemented and can be closed.
