### ISSUE TITLE
Cannot properly setup

### ISSUE THREAD

**Issue by qwang3** [Keck-DataReductionPipelines/KeckDRPFramework#51]
I was following the installation guide for the package, and when I ran `python setup.py install` I came across this error:

```
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    setup(
NameError: name 'setup' is not defined
```

I believe this is due to the fact that `setup()` is not explicitly imported in `setup.py`. When I add `from setuptools import setup` at the top of the file, the installation ran without an issue.

**Comment by shkw0k** [comment]
Thank you for reporting this bug.
I pushed a fix to master and develop.
