### ISSUE TITLE
The test harness (and probably the system) does not work unless PYTHONPATH is specified

### ISSUE THREAD

**Issue by lucarizzi** [Keck-DataReductionPipelines/KeckDRPFramework#8]
Standard execution of the test harness works:

sh runTest_harness.sh fits2png_pipeline config.cfg -d ../unit_tests/test_files

But running the test harness directly doesn't work:

python test_harness.py fits2png_pipeline config.cfg -d ../unit_tests/test_files
Failed loading pipeline fits2png_pipeline No module named 'fits2png_pipeline'
Failed loading pipeline pipelines.fits2png_pipeline No module named 'pipelines'
Failed loading pipeline test_pipelines.fits2png_pipeline No module named 'pipelines'
2019-11-08 11:14:33:DRPF:ERROR: Could not find pipeline fits2png_pipeline in ('', 'pipelines', 'test_pipelines')

And this is true even after a full installation of the package with:
python setup.py install

It is as if the search path for the pipelines depends on the correct settings for PYTHONPATH rather than using a package load system like package resources.

**Comment by lucarizzi** [comment]
This is now rather obvious. 
The way that the pipelines are loaded is via import lib.import_module
Clearly this works only if we provide the full path or if we add the pipeline directory to the search path.

I am not sure I like this method. I would prefer to make sure that all the pipelines have the same package structure, and they have directories called pipelines and primitives. 
Up for discussion.

**Comment by bjfultn** [comment]
I also don't like the idea of passing the pipeline names as strings. I propose that the framework is initialized with a Pipeline object that the user initializes before the framework object. I implemented this (because I needed it for KPF) in PR #6. Although I allowed for both options in that case, which is a bit hacky.

**Comment by lucarizzi** [comment]
Ok I’ll look at your code.

**Comment by bjfultn** [comment]
Its probably not clear from the Framework code, but here is how I'm using that in practice:
```
from kpfpipe.pipelines.KPF_pipeline import KPF_pipeline

config = ConfigClass(args.config_file)
framework = Framework(KPF_pipeline, config)
```

**Comment by lucarizzi** [comment]
Yes this is pretty clear and I like it

 

So essentially you are creating your own package, called kpfpipe and in there you have a pipeline subpackage that contains the definition of KPF_pipeline

 

Do you have a link to a github repository for that so that I reproduce the structure?

It would be very useful to come up with a standard, blank pipeline package

**Comment by bjfultn** [comment]
Yep, you should have just gotten an invite.

**Comment by shkw0k** [comment]
The framework is not the pipeline. 
When you install the framework, it does just that.
The pipeline that you build, is usually somewhere else and it may have a different directory structure.
It is up to the pipeline developer to define.

The script runTest_harness.sh is there to define the PYTHONPATH, which should be updated by the installation of the pipeline.

The reason to pass the name of the pipeline to the framework is that you don't need to modify the test_harness to run multiple pipelines, for example for multiple instruments.
Passing the pipeline object was the in the previous version and we needed different test_harnesses.

In the configuration file, there pipeline path and primitive path options to point to where to search.

**Comment by shkw0k** [comment]
There is also a template directory that contains a blank pipeline.
See make_copy.sh in that directory to create new pipeline.

**Comment by bjfultn** [comment]
```
The framework is not the pipeline.
When you install the framework, it does just that.
The pipeline that you build, is usually somewhere else and it may have a different directory structure.
It is up to the pipeline developer to define.
```
This makes sense, and the user pipelines really should be outside of the framework directory structure.

```
The script runTest_harness.sh is there to define the PYTHONPATH, which should be updated by the installation of the pipeline.

The reason to pass the name of the pipeline to the framework is that you don't need to modify the test_harness to run multiple pipelines, for example for multiple instruments.
Passing the pipeline object was the in the previous version and we needed different test_harnesses.

In the configuration file, there pipeline path and primitive path options to point to where to search.
```
What if the user's pipeline is `pip` installable? The user would then install their pipeline package without modifying the PYTHONPATH. In fact the user would have to go digging in their (anaconda) Python install or environment to find that directory. In addition, I can't use something like `kpfpipe.__file__` to find the directory programmatically because the config file is also specified as a string. 

I also had a lot of trouble specifying the path to my pipeline as something like:
`/Users/bfulton/anaconda3/lib/python3.7/site-packages/kpfpipe/pipelines` as the `pipeline_path` variable. I think this is because its doing something similar to `from blah import pipeline`, which doesn't work when `blah` looks like `/Users/bfulton/anaconda3/lib/python3.7/site-packages/kpfpipe/pipelines`.

**Comment by shkw0k** [comment]
The options pipeline_path and primitive_path are relative to PYTHONPATH.
They are in dot notation, like in the import statement.

So far I am not able to make it work when there are two directories called 'pipeline'. 
So I tried 'test_pipeline' and 'nires_pipeline' and that seems to work.

**Comment by lucarizzi** [comment]
May I suggest that we spend some time harmonizing the way that we are importing primitives and pipelines?

 

It seems as if both KPF and KCWI are using direct imports, such as:

 

From kcwipipeline.pipelines.KCWI_pipeline import kcwi_pipeline

 

And 

 

from kpfpipe.pipelines.KPF_pipeline import KPF_pipeline

 

config = ConfigClass(args.config_file)

framework = Framework(KPF_pipeline, config)

 

 

The idea here is that we generate a directory structure that looks like this:

 

Pipeline_name
primitives
pipelines
 

and Pipeline_name.pipelines becomes the name of the submodule to import from.

 

The idea of configuration paths and searching for the pipeline is rather powerful and very general but I am not so sure it is useful.

 

I’d like to agree on a common path before we go too far along the line of general imports from generic directories

 

I’ll talk to Shui tomorrow and maybe we can have a call at some point

**Comment by shkw0k** [comment]
This is easy change.
I will retain the string options and add passing the module as parameters and change the framework directories to framework_pipeline and framework_primitives.

**Comment by shkw0k** [comment]
Framework now can take string, module, class or object.
Also I added test_framework in unit_tests.
