### ISSUE TITLE
Python style convention

### ISSUE THREAD

**Issue by awhoward** [Keck-DataReductionPipelines/KeckDRPFramework#9]
Use the python style convention when naming functions and classes. An example of change would be `class BasePipeline` instead of `class base_pipeline`.  A long and detailed guide posted on the python page: https://www.python.org/dev/peps/pep-0008/.

In a thread elsewhere, @lucarizzi wrote:
> Yes, agreed. Astropy requires the code to be PEP8 compliant. Also, we want to use CI tools like Travis CI or similar. It hasn't been a huge priority in this early development phase but I agree. Note that it will break a few imports, but It's worth doing this now rather than later.
I will take this on on my own.

So how should this be implemented?

**Comment by shkw0k** [comment]
We can make the change now before the code base grows too big.
It will break a few things.

**Comment by shkw0k** [comment]
I made the changes to be PEP8 complaint. 
There are in the new develop branch.
